name: Frontend CI/CD
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint || echo "Линтинг не настроен, пропускаем"
      - run: npm run build
      - run: npm test -- --passWithNoTests
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build